import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  const url = new URL(request.url);
  const apiUrl = `${url.protocol}//${url.host}`;
  
  const content = `
// Configuration file for client-side environment variables
// Dynamically generated by server

window.APP_CONFIG = {
  API_URL: '${apiUrl}',
  API_PORT: '${url.port}'
};
  `;
  
  return new NextResponse(content, {
    headers: {
      'Content-Type': 'application/javascript',
    },
  });
}
